version:     "0018b--03-Aug-2021"
copyright:   "2021-2021"
description:
  This is a
  GitHub Page
disclaimer:
  I have spoken.
keywords:    "jekyll, testing"
navbarlinks:
- navbar:    "Home"
  link:      "/"
- navbar:    "Links"
  link:      "/LINKS/"
- navbar:    "Log"
  link:      "https://gloanda.github.io/os212/TXT/mylog.txt"
- navbar:    "GitHub"
  link:      "https://github.com/Gloanda/os212/"
- navbar:    "Listing"
  link:      "/000.html"
title:       "Operating Systems 2021-2 (OS212)"
lang:        "en-US"
author:      "Loanda Gunawan"
address:     "Tangerang"
sitemap:     "true"
markdown:    "kramdown"
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata
plugins:
- jekyll-sitemap
- jekyll-seo-tag
google_analytics: "UA-89852122-15"

urlweb:           "https://gloanda.github.io/os212/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/Gloanda/os212/"


